#!/usr/bin/env python3
"""
scripts/verify.py — Pi CI in a bottle.

Runs:
1. Syntax check on every .py file in the repo (ast.parse).
2. All non-costly tests under testing/ (excludes @pytest.mark.costly).
3. Writes docs/STATUS.md with date, results, and skipped tests.
4. Exits 0 if all pass, 1 otherwise.

Usage:
    python scripts/verify.py          # run everything
    python scripts/verify.py --quiet  # suppress per-file output
"""
import ast
import os
import sys
import subprocess
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).parent.parent
TESTING_DIR = ROOT / "testing"
STATUS_OUT = ROOT / "docs" / "STATUS.md"

COSTLY_TESTS = {
    "test_normie_honesty.py",
    "test_query_formulation.py",
    "test_memory_roundtrip.py",   # hits Claude API
    "test_memory_tool_path.py",   # T-023: hits Supabase + Claude API
    "test_l2_content_search.py",  # standalone script (no def test_*); run directly
    "test_runner.py",             # old harness class (TestRunner.__init__ confuses pytest)
}


def syntax_check_all() -> tuple[list[str], list[str]]:
    """Return (passed_paths, failed_paths) for all .py files in the repo."""
    passed, failed = [], []
    for path in sorted(ROOT.rglob("*.py")):
        # skip venv, __pycache__, .git
        if any(part in path.parts for part in ("pi_env", "__pycache__", ".git")):
            continue
        try:
            ast.parse(path.read_text(encoding="utf-8", errors="replace"))
            passed.append(str(path.relative_to(ROOT)))
        except SyntaxError as e:
            failed.append(f"{path.relative_to(ROOT)}:{e.lineno}: {e.msg}")
    return passed, failed


def run_tests() -> tuple[list[str], list[str], list[str]]:
    """Return (run_tests, skipped_tests, failures) from the non-costly suite."""
    test_files = sorted(TESTING_DIR.glob("test_*.py"))
    run, skipped, failures = [], [], []

    for tf in test_files:
        if tf.name in COSTLY_TESTS:
            skipped.append(tf.name)
            continue

        result = subprocess.run(
            [sys.executable, "-m", "pytest", str(tf), "-q", "--tb=short",
             "-m", "not costly"],
            capture_output=True, text=True, cwd=ROOT
        )
        run.append(tf.name)
        if result.returncode != 0:
            failures.append(f"FAIL {tf.name}:\n{result.stdout[-800:]}\n{result.stderr[-400:]}")

    return run, skipped, failures


def write_status(
    syntax_passed: list[str],
    syntax_failed: list[str],
    tests_run: list[str],
    tests_skipped: list[str],
    test_failures: list[str],
) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    overall = "PASS" if not syntax_failed and not test_failures else "FAIL"

    lines = [
        f"# docs/STATUS.md — auto-generated by scripts/verify.py",
        f"",
        f"**Last run:** {now}",
        f"**Overall:** {overall}",
        f"",
        f"---",
        f"",
        f"## Syntax check",
        f"",
        f"- Files checked: {len(syntax_passed) + len(syntax_failed)}",
        f"- Passed: {len(syntax_passed)}",
        f"- Failed: {len(syntax_failed)}",
    ]
    if syntax_failed:
        lines.append("")
        lines.append("**Failures:**")
        for f in syntax_failed:
            lines.append(f"- `{f}`")

    lines += [
        f"",
        f"---",
        f"",
        f"## Test suite (non-costly)",
        f"",
        f"- Tests run: {len(tests_run)}",
        f"- Skipped (costly): {len(tests_skipped)}",
        f"- Failures: {len(test_failures)}",
    ]
    if tests_run:
        lines.append("")
        lines.append("**Run:**")
        for t in tests_run:
            mark = "✅" if not any(t in f for f in test_failures) else "❌"
            lines.append(f"- {mark} `{t}`")
    if tests_skipped:
        lines.append("")
        lines.append("**Skipped (run manually — hit live APIs):**")
        for t in tests_skipped:
            lines.append(f"- ⏭ `{t}`")
    if test_failures:
        lines.append("")
        lines.append("**Failure detail:**")
        for f in test_failures:
            lines.append("")
            lines.append("```")
            lines.append(f)
            lines.append("```")

    STATUS_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    quiet = "--quiet" in sys.argv

    print("[verify] Syntax check...")
    syn_pass, syn_fail = syntax_check_all()
    if not quiet:
        for f in syn_fail:
            print(f"  SYNTAX FAIL: {f}")
    print(f"  {len(syn_pass)} ok, {len(syn_fail)} failed")

    print("[verify] Running non-costly tests...")
    t_run, t_skip, t_fail = run_tests()
    if not quiet:
        for f in t_fail:
            print(f"\n{f}")
    print(f"  {len(t_run)} run, {len(t_skip)} skipped, {len(t_fail)} failed")

    print(f"[verify] Writing {STATUS_OUT.relative_to(ROOT)}...")
    write_status(syn_pass, syn_fail, t_run, t_skip, t_fail)

    ok = not syn_fail and not t_fail
    print(f"[verify] {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
